name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build ${{matrix.os}}/${{matrix.build-type}}
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Fetch code-signing key
        if: matrix.os == 'windows'
        env:
          CODE_SIGNING_PFX_BASE64: ${{ secrets.CODE_SIGNING_PFX_BASE64 }}
        run: '[System.Convert]::FromBase64String($Env:CODE_SIGNING_PFX_BASE64) | Set-Content ${{runner.temp}}/MyCert.pfx -AsByteStream'
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          cmake ${{github.workspace}}/source `
            "-DSIGNTOOL_KEY_ARGS=/f;${{runner.temp}}/MyCert.pfx" `
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} `
            "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/com.fredemmott.micmutetoggle.sdPlugin"
      - name: Compile
        working-directory: build
        run: cmake --build . --config ${{matrix.build-type}} --parallel
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.build-type}}
      - name: Upload MacOS Executable
        if: matrix.os == 'macos'
        uses: actions/upload-artifact@v2
        with:
          name: Mac-${{matrix.build-type}}
          path: build/Sources/sdmicmute
      - name: Upload Windows Executable
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v2
        with:
          name: Windows-${{matrix.build-type}}
          path: build/Sources/${{matrix.build-type}}/sdmicmute.exe
      - name: Upload Windows Debug Symbols
        if: matrix.os == 'windows' && matrix.build_type != 'Release'
        uses: actions/upload-artifact@v2
        with:
          name: Windows-${{matrix.build-type}}
          path: build/Sources/${{matrix.build-type}}/sdmicmute.pdb
    strategy:
      matrix:
        os: [windows, macos]
        build-type: [RelWithDebInfo, Debug]
  streamDeckPlugin:
    name: streamDeckPlugin/${{matrix.build-type}}
    needs: [build]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          cmake ${{github.workspace}}/source `
            "-DCMAKE_INSTALL_PREFIX=${{runner.temp}}/com.fredemmott.micmutetoggle.sdPlugin"
      - name: Install static files
        working-directory: build/sdPlugin
        run: make install
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{runner.temp}}/artifacts
      - name: Display downloaded files
        run: ls -R
        working-directory: ${{runner.temp}}/artifacts
      - name: Copy executables
        working-directory: ${{runner.temp}}
        run: |
          install -m755 \
            artifacts/Mac-${{matrix.build-type}}/sdmicmute \
            com.fredemmott.micmutetoggle.sdPlugin/sdmicmute
          install -m755 \
            artifacts/Windows-${{matrix.build-type}}/sdmicmute.exe \
            com.fredemmott.micmutetoggle.sdPlugin/sdmicmute.exe
          PDB_SRC=artifacts/Windows-${{matrix.build-type}}/sdmicmute.pdb
          if [ -e $PDB_SRC]; then
            install -m755 \
              ${PDB_SRC} \
              com.fredemmott.micmutetoggle.sdPlugin/sdmicmute.pdb
          fi
      - name: Checkout DistributionTool
        uses: actions/checkout@v2
        with:
          ref: distributiontool-v1.4
      - name: Build .streamDeckPlugin
        run: |
          ./DistributionTool -b \
            -i ${{runner.temp}}/com.fredemmott.micmutetoggle.sdPlugin \
            -o .
      - name: Upload .streamDeckPlugin
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build-type}}-StreamDeckPlugin
          path: com.fredemmott.micmutetoggle.streamDeckPlugin
    strategy:
      matrix:
        build-type: [RelWithDebInfo, Debug]
  release:
    needs: [streamDeckPlugin]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ${{runner.temp}}/artifacts
    - name: Display downloaded files
      run: ls -R
      working-directory: ${{runner.temp}}/artifacts
    - name: Check if this is a release push
      id: ref
      run: |
        if echo ${{github.ref}} | grep --silent refs/tags/v; then
          echo "::set-output name=is-release::true"
          echo "::set-output name=tag::$(echo ${{github.ref}} | awk -F/ '{print $NF}')"
        else
          echo "::set-output name=is-release::false"
        fi
    - name: Create Draft Release
      id: create-release
      if: steps.ref.outputs.is-release == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ steps.ref.outputs.tag }}
        tag_name: ${{steps.ref.outputs.tag}}
        draft: true
    - name: Attach Release Build
      if: steps.ref.outputs.is-release == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{runner.temp}}/artifacts/RelWithDebInfo-StreamDeckPlugin/com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_name: com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_content_type: application/octet-stream
    - name: Attach Debug Build
      if: steps.ref.outputs.is-release == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{runner.temp}}/artifacts/Debug-StreamDeckPlugin/com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_name: debug-com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_content_type: application/octet-stream
